using System;

	
	public class Program{
 	public static void Main()
	{
		int a=5;
		int[] arr = new int[2];
		try{
			Console.WriteLine(arr[2]);
            }
		catch
		{
			Console.WriteLine("Some exception occurs");
		}
            Console.ReadLine();
	}
	}
	