using System;

	
	public class Program{
 	public static void Main()
	{
		int a=5;
		int[] arr = new int[2];
		try{
			Console.WriteLine(arr[2]);
            }
		catch(Exception e) 
		{
			Console.WriteLine("exception is : "+e.Message+"\n error occur at"+e.StackTrace);
		}
            Console.ReadLine();
	}
	}